### PR TITLE
Ipv4 fixes

### LINKED ISSUE #154: Fix support for IPv4
It appears that communication between IPv4 endpoints doesn't currently work, while communication between IPv6 endpoints does. Tested with 127.0.0.1 and [::1].

### PR DESCRIPTION
**Pull request by Ralith**
Fix #154

I wasn't sure whether to branch based on the type of the destination address or the type of the local address. I opted for the former since it allows the OS to provide its usual error message when an unsupported address is used.

It's interesting to note that an "Address family not supported by protocol" error currently brings down the whole endpoint. Perhaps send errors should be propagated back to their associated connection instead?

### CODE REVIEW

File: quinn/src/lib.rs [hunk 1]
```diff
@@ -788,8 +785,13 @@ impl Future for Driver {
                         packet,
                         ecn,
                     } => {
+                        let destination = if let Some(v4) = destination.ip().to_ipv4() {
```
Comment (djc) [inline quinn/src/lib.rs]: Putting this here means we have to do run through this conversion on every send, which seems a little wasteful? As I understand it, the destination will not change very often over time.

Comment (Ralith) [reply quinn/src/lib.rs]: Right, per connection it doesn't change, just per send call. I suppose we could switch to storing generic `SocketAddr`s in `Connection`, and only use normalized `SocketAddrV6` for hash table keys, it just feels a little silly when that doesn't actually increase expressiveness any.

Comment (djc) [reply quinn/src/lib.rs]: Maybe, but it seems preferable over converting the address for every send.

**Comment by djc** [comment]
Much better! Probably squash those "Send to..." and "Move SocketAddr..." commits?

**Comment by Ralith** [comment]
Squashed.
