### PR TITLE
Fixed active connection ID window

### LINKED ISSUE #670: Intermittent CONNECTION_ID_LIMIT_ERROR with git master
On git master, I intermittently run into a CONNECTION_ID_LIMIT_ERROR which causes my tests to fail every few thousand iterations.  I am not sure if this is a regression in my code or in `quinn-proto`.

### PR DESCRIPTION
**Pull request by Ralith**
Fixes #670. This was ~a long-standing bug~ multiple long-standing bugs revealed by the stricter protocol requirements in draft 27.

### CODE REVIEW

**Comment by Ralith** [comment]
On review this still isn't quite right, but it's close. Need to make sure the currently selected CID is always the lower end of the window. Will revise tomorrow.

File: quinn-proto/src/connection.rs [hunk 1]
```diff
@@ -151,7 +153,12 @@ where
 
     streams: Streams,
     /// Surplus remote CIDs for future use on new paths
-    rem_cids: Vec<IssuedCid>,
+    ///
+    /// Sequence numbers start at `self.first_unretired_cid` and are contiguous, including `None`
+    /// slots. Always exactly REM_CID_COUNT elements long. Maintaining a fixed-size window allows us
+    /// to easily discard duplicate and obsolete NEW_CONNECTION_ID frames fast and with constant
+    /// memory.
+    rem_cids: VecDeque<Option<(ConnectionId, ResetToken)>>,
```
Comment (djc) [inline quinn-proto/src/connection.rs]: I find the design here quite complex. Did you think about storing the sequence numbers in the deque along with the other state instead (it would become `VecDeque<(u64, Option<(ConnectionId, ResetToken)>)>`, I guess)? This should obviate the need for the separate `first_unretired_cid`. It would take a bit of extra memory, but 64 every bytes in the heap probably won't kill us.

(Perhaps `(u64, Option<(ConnectionId, ResetToken)>)` should become a proper struct instead, in which case we can also derive `Default` for it.)

Comment (Ralith) [reply quinn-proto/src/connection.rs]: We're specifically trying to represent a continuous sliding window. I'm hence not a fan of explicit sequence numbers, because they allow a far larger number of invalid states to be represented. The latest iteration of this is hopefully a bit clearer.

**Comment by djc** [comment]
Yeah, that does look better. I do feel like this would probably be better as an explicit struct with an abstract interface wrapped around it, since it seems like it could hide a lot of the complexity. If we do that, it might also be more feasible to use an array with a cursor pointer rather than a `VecDeque<Option<>>`.
