### PR TITLE
Keep defragmented in sync with data length (fixes #639)

### LINKED ISSUE #639: Integer overflow running benchmark
Running a minimally changed version of https://github.com/djc/quinn/blob/605c9a57efd89055118232fbb9eee3728e68ffbb/quinn/benches/bench.rs, in release mode with `overflow-checks = true`, triggers integer overflow here:

https://github.com/djc/quinn/blob/605c9a57efd89055118232fbb9eee3728e68ffbb/quinn-proto/src/assembler.rs#L128

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /Users/alecmocatta/.cargo/git/checkouts/quinn-572d2e5812b43165/605c9a5/quinn-proto/src/assembler.rs:128:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/alecmocatta/.cargo/git/checkouts/quinn-572d2e5812b43165/605c9a5/quinn/src/connection.rs:500:26
stack backtrace:
   0:        0x10828236f - backtrace::backtrace::libunwind::trace::hcfa7701d6c81f8a0
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:        0x10828236f - backtrace::backtrace::trace_unsynchronized::h779bbcc9c02b9355
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:        0x10828236f - std::sys_common::backtrace::_print_fmt::habf57f6a558eac94
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x10828236f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc660489926238a51
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10829b39e - core::fmt::write::h85d7f7431aad7c6e
                               at src/libcore/fmt/mod.rs:1052
   5:        0x10827e3cb - std::io::Write::write_fmt::hea8e7fea3b67f600
                               at src/libstd/io/mod.rs:1428
   6:        0x10828426a - std::sys_common::backtrace::_print::h8291258e26c6cac9
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10828426a - std::sys_common::backtrace::print::h9022c7942b3bfada
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10828426a - std::panicking::default_hook::{{closure}}::h594982c6a4b10b79
                               at src/libstd/panicking.rs:204
   9:        0x108283f92 - std::panicking::default_hook::hc433e2981735fb5f
                               at src/libstd/panicking.rs:224
  10:        0x1082848d8 - std::panicking::rust_panic_with_hook::heea00f89b45f5ac9
                               at src/libstd/panicking.rs:470
  11:        0x1082844a2 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:        0x1082a9d1f - core::panicking::panic_fmt::he90b7accb40987e1
                               at src/libcore/panicking.rs:85
  13:        0x1082a9c25 - core::option::expect_none_failed::h1dce1765a6e65857
                               at src/libcore/option.rs:1211
  14:        0x108185a20 - core::result::Result<T,E>::unwrap::hd19ed174e2bc26a1
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/result.rs:1003
  15:        0x108185a20 - <quinn::connection::ConnectionRef as core::ops::drop::Drop>::drop::hc28a16f930a57c73
                               at /Users/alecmocatta/.cargo/git/checkouts/quinn-572d2e5812b43165/605c9a5/quinn/src/connection.rs:500
  16:        0x10816d0ca - core::ptr::drop_in_place::hf63a3652f375bdb6
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  17:        0x10816d0ca - core::ptr::drop_in_place::h8de588d8ca53b3d2
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  18:        0x10816d0ca - core::ptr::drop_in_place::hf88042267b8e179e
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  19:        0x10816d0ca - core::ptr::drop_in_place::he25e1680f2068a41
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  20:        0x10816d0ca - tokio::task::core::Core<T>::transition_to_consumed::h01876de0bf6bc76f
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/core.rs:106
  21:        0x10816747b - tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}::haffc660f700161bc
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:126
  22:        0x10816747b - core::ops::function::FnOnce::call_once::h4b692cb3c3e83c6e
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ops/function.rs:232
  23:        0x10816747b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6b41556582c14c56
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:318
  24:        0x10816747b - std::panicking::try::do_call::h644839c70adebacb
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:303
  25:        0x10828716b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  26:        0x1081544b3 - std::panicking::try::h9c99218bffcf36f0
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:281
  27:        0x1081544b3 - std::panic::catch_unwind::h145d755f68975d9b
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:394
  28:        0x1081544b3 - tokio::task::harness::Harness<T,S>::poll::{{closure}}::h2d71f5bf917cdc27
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:101
  29:        0x1081544b3 - tokio::loom::std::causal_cell::CausalCell<T>::with_mut::h1dc8c16d5339c41a
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/loom/std/causal_cell.rs:41
  30:        0x1081544b3 - tokio::task::harness::Harness<T,S>::poll::h2a54ba8f01e5bb0b
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:100
  31:        0x108113023 - tokio::task::Task<S>::run::hcd1e30877ee61b87
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/mod.rs:381
  32:        0x108113023 - tokio::runtime::basic_scheduler::SchedulerPriv::tick::h917eb64bf45083aa
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:192
  33:        0x108113650 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hab421b76582fd629
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:142
  34:        0x108100b11 - tokio::runtime::Runtime::block_on::{{closure}}::h57899e3815a66ef0
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:411
  35:        0x108100b11 - tokio::runtime::context::enter::hec9e6bb65c0f0549
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  36:        0x10810d1c6 - tokio::runtime::handle::Handle::enter::heb7a252a9c0e41b4
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  37:        0x10810d1c6 - tokio::runtime::Runtime::block_on::h9b6273f3f985a47d
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  38:        0x10810d1c6 - test::spawn_server::{{closure}}::h62475fbb8124bd5a
                               at src/main.rs:105
  39:        0x10810d1c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb8225a0178067684
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/sys_common/backtrace.rs:130
  40:        0x108103270 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9d88c8a9390b5971
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/thread/mod.rs:475
  41:        0x108103270 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h70c8f109d72539e1
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:318
  42:        0x108103270 - std::panicking::try::do_call::he5cd41b3367eb81c
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:303
  43:        0x10828716b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  44:        0x10810d927 - std::panicking::try::h2a953fce4733d488
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:281
  45:        0x10810d927 - std::panic::catch_unwind::hce7043a1298225f9
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:394
  46:        0x10810d927 - std::thread::Builder::spawn_unchecked::{{closure}}::h76b83e07da2f1f27
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/thread/mod.rs:474
  47:        0x10810d927 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4741f86a2216ad6d
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ops/function.rs:232
  48:        0x10827b2ae - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h592c882fdd157300
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/liballoc/boxed.rs:1017
  49:        0x1082866fe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb029a45d53c19f17
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/liballoc/boxed.rs:1017
  50:        0x1082866fe - std::sys_common::thread::start_thread::h0d619f871e1f2510
                               at src/libstd/sys_common/thread.rs:13
  51:        0x1082866fe - std::sys::unix::thread::Thread::new::thread_start::hbc17962bf915d96d
                               at src/libstd/sys/unix/thread.rs:80
  52:     0x7fff625812eb - <unknown>
  53:     0x7fff62584249 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction: 4
```

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

File: quinn-proto/src/assembler.rs [hunk 1]
```diff
@@ -113,6 +113,7 @@ impl Assembler {
     }
 
     pub(crate) fn pop(&mut self) -> Option<(u64, Bytes)> {
```
Comment (Ralith) [inline quinn-proto/src/assembler.rs]: Should `read` call this rather than more or less duplicating its logic?

Comment (djc) [reply quinn-proto/src/assembler.rs]: Good call, fixed.
