### PR TITLE
Connection lifecycle fixes

### LINKED ISSUE #331: Remotely-initiated streams should be accessible on closed connections
In the case where the peer creates a stream, sends less than a flow control window's worth of data, finishes it, and then closes the connection, the high-level interface will currently prevent the local application from reading the stream if the close is processed before the application has a chance to accept the stream, even though the stream was reliably delivered.

### PR DESCRIPTION
**Pull request by Ralith**
Looks like we forgot to update `quinn::Incoming` to yield a stream of handshake futures to represent the fact that its connections are not yet fully established.

Fixes #331

### CODE REVIEW

File: quinn/src/connection.rs [hunk 1]
```diff
@@ -19,15 +19,18 @@ use tokio_timer::Delay;
...
+/// Be sure to spawn the `ConnectionDriver` when complete.
 pub struct Connecting(Option<ConnectionDriver>);
 
 impl Connecting {
     pub(crate) fn new(conn: ConnectionRef) -> Self {
         Self(Some(ConnectionDriver(conn)))
     }
 
-    /// Convert into a 0-RTT or 0.5-RTT connection at the cost of weakened security
+    /// Convert into a 0-RTT or 0.5-RTT connection at the cost of weakened security. Be sure to
```
Comment (djc) [inline quinn/src/connection.rs]: Hmm, so I think it should go after the newline here too, and in the third hunk as well. Otherwise the rustdocs will look weird.

Comment (Ralith) [reply quinn/src/connection.rs]: Current rustdoc doesn't seem to treat the first line of method documentation specially, unless I'm missing something.

Comment (djc) [reply quinn/src/connection.rs]: Ah, you're right, it doesn't matter for methods!
